Core 2.0 compatible unified extension API changes
adobe/aepsdk-optimize-android pull request #34
Opened 2022-11-10 18:39 UTC by spoorthipujariadobe

## Description

1. Upgraded Java version , min, target and compile SDK versions
2. Use new `Log` service instead of `MobileCore.log`.
3. Replaced as `ExtensionListener` classes with `ExtensionEventListener` interface.
4. Replaced `MobileCore.dispatchEvent` with new method signature.
5. Replaced `MobileCore.dispatchEvent` in Extension class with `ExtensionApi.dispatch`
6. Modified public API class for new `registerExtensions` method and deprecated older `registerExtension` method.
7. Removed executor service usage in Extension class.
8. Added configuration dependency in `readyForEvent` and used new `getSharedState` API.
9. Replaced most casts with `DataReader`.
10. Added in checkstyle for code linting.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-11-16 16:48 UTC, swarna04 requested changes

2022-11-16 16:48 UTC, swarna04 commented on code/optimize/src/test/java/com/adobe/marketing/mobile/optimize/OptimizeTests.java
> +            mobileCoreMockedStatic.verify(() -> MobileCore.dispatchEvent(eventCaptor.capture()), times(1));
nit: `times(1)` is redundant here as `mobileCoreMockedStatic.verify(() -> MobileCore.dispatchEvent(eventCaptor.capture()));` verifies that certain behavior happened once. It is 
alias to verify(mock, times(1)). Check this in other tests as well.

2022-11-16 16:48 UTC, swarna04 commented on code/optimize/src/test/java/com/adobe/marketing/mobile/optimize/OptimizeTests.java
> +            ArgumentCaptor<ExtensionErrorCallback> callbackCaptor = ArgumentCaptor.forClass(
Declare variables `final` e.g. final ArgumentCaptor<Class> extensionClassCaptor = ...

2022-11-16 16:48 UTC, swarna04 commented on code/optimize/src/test/java/com/adobe/marketing/mobile/optimize/OptimizeTests.java
> +            ArgumentCaptor<ExtensionErrorCallback> callbackCaptor = ArgumentCaptor.forClass(
Declare variables final e.g. `final` ArgumentCaptor extensionClassCaptor = ...

2022-11-16 16:48 UTC, swarna04 commented on code/optimize/src/test/java/com/adobe/marketing/mobile/optimize/OptimizeTests.java
> +            callbackCaptor.getValue().error(ExtensionError.UNEXPECTED_ERROR);
nit: This `test_registerExtension()` should ideally be happy path test.  So test for `callbackCaptor.getValue().error(null);` in this test.

2022-11-16 16:48 UTC, swarna04 commented on code/optimize/src/test/java/com/adobe/marketing/mobile/optimize/OptimizeTests.java
> +            callbackCaptor.getValue().error(null);
Suggest re-write
```
 @Test
    public void test_registerExtension_extensionError() {
        try (MockedStatic<MobileCore> mobileCoreMockedStatic = Mockito.mockStatic(MobileCore.class);
             MockedStatic<Log> logMockedStatic = Mockito.mockStatic(Log.class)) {
            // setup
            final ArgumentCaptor<Class> extensionClassCaptor = ArgumentCaptor.forClass(Class.class);
            final ArgumentCaptor<ExtensionErrorCallback> callbackCaptor = ArgumentCaptor.forClass(
                    ExtensionErrorCallback.class
            );
            mobileCoreMockedStatic
                    .when(() -> MobileCore.registerExtension(extensionClassCaptor.capture(), callbackCaptor.capture()))
                    .thenReturn(true);
            // test
            Target.registerExtension();

            // verify
            assertNotNull(callbackCaptor.getValue());
            assertEquals(TargetExtension.class, extensionClassCaptor.getValue());
            
            callbackCaptor.getValue().error(ExtensionError.UNEXPECTED_ERROR);
            logMockedStatic.verify(() -> Log.warning(anyString(), anyString(), anyString(), any()));
        }
    }
```

2022-11-16 17:36 UTC, spoorthipujariadobe commented on code/optimize/src/main/java/com/adobe/marketing/mobile/optimize/DecisionScope.java
> +    private static final String SELF_TAG = "DecisionScope";
The class name can get obfuscated if the app enables minify, so hard coding it. Following this convention from other core extensions https://github.com/adobe/aepsdk-core-android/blob/97622211024840a0bb3c1e99559535481b8a8365/code/android-signal-library/src/phone/java/com/adobe/marketing/mobile/Signal.java#L19

2022-11-17 02:28 UTC, spoorthipujariadobe commented on code/optimize/src/main/java/com/adobe/marketing/mobile/optimize/Proposition.java
> +            // todo
`todo` was to replace casting with `DataReader` usage once nested generic types are supported. No sure if Core will add it. Will remove the `todo` once we decide on it

2022-11-17 02:58 UTC, spoorthipujariadobe commented on code/optimize/src/main/java/com/adobe/marketing/mobile/optimize/Offer.java
> +    @SuppressWarnings("checkstyle:nestedifdepth")
Added max depth as 3, will share internally but might be an extension specific setting

2022-11-17 14:16 UTC, swarna04 requested changes
Apologies! Adding additional feedback comments from a couple of files that I missed adding before.

2022-11-17 23:09 UTC, spoorthipujariadobe commented on code/optimize/src/main/java/com/adobe/marketing/mobile/optimize/Optimize.java
> +                // todo
`todo` was for potential `DataReader` usage. Will fix once Core team clarifies support for reading nested collections.

2022-11-17 23:09 UTC, spoorthipujariadobe commented on code/optimize/src/main/java/com/adobe/marketing/mobile/optimize/Optimize.java
> +                // todo
Same as above

2022-11-17 23:12 UTC, spoorthipujariadobe commented on code/optimize/src/main/java/com/adobe/marketing/mobile/optimize/OptimizeExtension.java
> +            // todo
Placeholder for `DataReader`

2022-11-17 23:13 UTC, spoorthipujariadobe commented on code/optimize/src/main/java/com/adobe/marketing/mobile/optimize/OptimizeExtension.java
> +            // todo
Placeholder for DataReader

2022-11-17 23:30 UTC, spoorthipujariadobe commented on code/optimize/src/main/java/com/adobe/marketing/mobile/optimize/OptimizeExtension.java
> +        eventData.put(OptimizeConstants.EventDataKeys.RESPONSE_ERROR, error.getErrorName());
`setEventData` is throwing serialization error with custom objects. I have informed this to core team. Added `todo`, will add a fix once they expose some methods to convert it

2022-11-18 22:32 UTC, spoorthipujariadobe commented on code/optimize/src/main/java/com/adobe/marketing/mobile/optimize/OptimizeExtension.java
> +        eventData.put(OptimizeConstants.EventDataKeys.RESPONSE_ERROR, error.getErrorName());
Discussed offline, will be passing `error.getErrorCode`. Using the error code to reconstruct `AdobeError` in Public API response callback

2022-12-13 18:34 UTC, merged